# This is a TOML document.

title = "TOML Demo"

[owner]
name = "nico1988"
dob = "2020-12-17"

[database]
server = "192.168.1.2"
ports = [9001, 9001, 9002]
connection_max = 9000
enabled = true

[servers]

[servers.alpha]
ip = "10.0.0.5"
dc = "eqdc11"

[servers.beta]
ip = "10.0.0.5"
dc = "eqdc11"

[clients]
data = [["gamma", "delta"], [1, 2]]

hosts = ["alpha", "omega"]
